import test from 'node:test';
import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {WORLD,terrainBlocked} from '../src/rover/data.js';
import {BUILDINGS,STREET_PROPS,GROUND_DETAILS,ROAD_DASHES,inIsland,compoundFootprint} from '../src/rover/terrain-scene.js';
import {RoverTerrain,TERRAIN_CHUNK,TERRAIN_CACHE_LIMIT} from '../src/rover/terrain.js';
const ctx=()=>new Proxy({},{get(t,k){return k in t?t[k]:()=>{};}});
test('terrain paints each whole illustrated location once, with no loose roof or raised-prop layer',()=>{
  const {terrain}=harness(),calls=[];terrain.sprite=(c,group,id,o)=>calls.push({group,id,o});terrain.paint(ctx(),{x:0,y:0,w:WORLD.w,h:WORLD.h});
  const locations=calls.filter(o=>o.group==='compounds');assert.equal(locations.length,BUILDINGS.length);assert.ok(locations.every((o,i)=>o.id===BUILDINGS[i].id));assert.ok(!calls.some(o=>o.group==='buildings'));
});
function harness(){const sizes=[],out=ctx(),images={compoundsA:{width:1254,height:1254},compoundsB:{width:1254,height:1254},scenery:{width:1254,height:1254},extraction:{width:1145,height:1374}},terrain=new RoverTerrain(images,(w,h)=>{sizes.push([w,h]);return{width:w,height:h,getContext:()=>ctx()};});return{terrain,out,sizes};}
test('near-view ground uses native detail chunks, not the overview bitmap or a giant full-world canvas',()=>{const {terrain,out,sizes}=harness();terrain.draw(out,{x:3000,y:3100,w:430,h:930},2);assert.equal(terrain.ratio,2);assert.ok(terrain.chunks.size>=6);assert.ok(terrain.chunks.size<=12);assert.ok(sizes.every(([w,h])=>w===(TERRAIN_CHUNK+4)*2&&h===w));const built=terrain.builds;for(let i=0;i<120;i++)terrain.draw(out,{x:3000,y:3100,w:430,h:930},2);assert.equal(terrain.builds,built);const source=readFileSync(new URL('../src/rover/render.js',import.meta.url),'utf8');assert.doesNotMatch(source,/images\.map/);assert.match(source,/terrain\.draw\(/);});
test('whole illustrated compounds cover every island without assembling loose buildings or props',()=>{assert.equal(new Set(BUILDINGS.map(o=>o.island)).size,26);assert.ok(BUILDINGS.length>=26&&BUILDINGS.length<60);assert.equal(STREET_PROPS.length,0);assert.ok(GROUND_DETAILS.length>=300);assert.ok(ROAD_DASHES.length>=400);assert.equal(new Set(BUILDINGS.map(o=>o.id)).size,8);for(const o of BUILDINGS){assert.ok(compoundFootprint(o).every(p=>inIsland(p,o.island)));assert.ok(terrainBlocked(o.x,o.y,0));assert.ok(o.w<=580);}for(const o of GROUND_DETAILS)assert.equal(terrainBlocked(o.x,o.y,8),false,o.id);});
test('chunk LRU stays bounded while visiting the entire city and density changes invalidate only visual cache',()=>{const {terrain,out}=harness();for(let y=200;y<WORLD.h;y+=470)for(let x=200;x<WORLD.w;x+=540){terrain.draw(out,{x,y,w:430,h:930},2);assert.ok(terrain.chunks.size<=TERRAIN_CACHE_LIMIT);}const before=terrain.builds;terrain.draw(out,{x:3000,y:3100,w:430,h:930},1);assert.equal(terrain.ratio,1);assert.ok(terrain.builds>before);assert.ok(terrain.chunks.size<=12);assert.equal(terrain.overview,null);});
test('minimap and full map reuse one overview rendered from exactly the live terrain scene',()=>{const {terrain,out,sizes}=harness();terrain.drawOverview(out,0,0,59,59);const overview=terrain.overview;assert.ok(overview);for(let i=0;i<30;i++)terrain.drawOverview(out,20,100,340,340);assert.equal(terrain.overview,overview);assert.deepEqual(sizes,[[640,640]]);});
test('failed canvas cache allocation still draws the same real terrain and sprites without stand-ins',()=>{const images={compoundsA:{width:1254,height:1254},compoundsB:{width:1254,height:1254},scenery:{width:1254,height:1254}},calls=[],out=ctx();out.drawImage=(...args)=>calls.push(args[0]);const terrain=new RoverTerrain(images,()=>null);terrain.draw(out,{x:600,y:600,w:900,h:900},2);assert.ok(calls.includes(images.compoundsA));assert.ok(calls.includes(images.scenery));assert.equal(terrain.chunks.size,0);});
