import test from 'node:test';
import assert from 'node:assert/strict';
import {RoverGame} from '../src/rover/game.js';
import {SAVE_KEY,newProfile,DRIVE,WORLD,MODULE_BY_ID} from '../src/rover/data.js';
import {IMAGES} from '../src/rover/assets.js';
import {grantXP} from '../src/rover/rogue.js';
const copy=v=>v===undefined?undefined:JSON.parse(JSON.stringify(v));
function harness(initial={},fail=null){
  const data=new Map(Object.entries(initial)),writes=[],paths=[];
  const ctx=new Proxy({createLinearGradient:()=>({addColorStop(){}}),measureText:s=>({width:[...s].length*7})},{get(t,k){return k in t?t[k]:()=>{};}});
  const canvas={getContext:()=>ctx,width:390,height:844};
  const storage={get:k=>copy(data.get(k)),set:(k,v)=>{writes.push(k);data.set(k,copy(v));return true;}};
  const createImage=()=>({width:1254,height:1254,set src(url){paths.push(url);queueMicrotask(()=>url===fail?this.onerror():this.onload());}});
  const game=new RoverGame({canvas,createImage,createSurface:()=>({width:1254,height:1254,getContext:()=>ctx}),storage});game.resize({width:390,height:844,dpr:2});return{game,data,writes,paths};
}
async function loaded(initial={},fail=null){const h=harness(initial,fail);await h.game.load();return h;}
function frames(g,seconds,start=0){g.frame(start);for(let i=1;i<=Math.ceil(seconds*60);i++)g.frame(start+i*1000/60);}
function click(g,id,pointer=1){const b=g.renderer.buttons.find(b=>b.id===id);assert.ok(b,'visible button '+id);g.pointerDown(b.x+b.w/2,b.y+b.h/2,pointer);g.pointerUp(b.x+b.w/2,b.y+b.h/2,pointer);}
test('independent workshop navigation ignores hidden equipment actions and returns to the same equipment page',async()=>{
  const {game:g}=await loaded({[SAVE_KEY]:{...newProfile(),bank:1000}});g.action('module:rocket');assert.equal(g.screen,'garage');
  click(g,'arsenal');assert.equal(g.gearPage,1);assert.equal(g.screen,'workshop');click(g,'module:rocket');g.keyboard('enter',true);g.keyboard('enter',false);assert.equal(g.screen,'module');assert.equal(g.run,null);
  click(g,'equip');assert.equal(g.profile.bank,150);assert.equal(g.screen,'workshop');assert.equal(g.gearPage,1);assert.deepEqual(g.profile.equipped,['rocket']);
  click(g,'module:rocket');g.keyboard('escape',true);g.keyboard('escape',false);assert.equal(g.screen,'workshop');g.keyboard('escape',true);g.keyboard('escape',false);assert.equal(g.screen,'garage');assert.equal(g.run,null);
});
test('level-up freezes combat and survives reload; choice resumes without offline catch-up',async()=>{const h=await loaded(),g=h.game;g.start();grantXP(g.run,8);frames(g,.1);assert.equal(g.screen,'upgrade');assert.deepEqual(g.input,{x:0,y:0});const time=g.run.time,offers=[...g.run.rogue.offer];frames(g,10,200);assert.equal(g.run.time,time);assert.equal(g.renderer.buttons.filter(b=>b.id.startsWith('pick:')).length,3);const r=await loaded(Object.fromEntries(h.data));r.game.start();assert.equal(r.game.screen,'upgrade');assert.deepEqual(r.game.run.rogue.offer,offers);r.game.keyboard('1',true);assert.equal(r.game.screen,'play');assert.equal(r.game.run.rogue.levels[offers[0]],1);frames(r.game,.1,1e9);assert.ok(r.game.run.time-time<.11);});
test('base is uncluttered; workshop pages and detail views fit smallest portrait viewport',async()=>{const {game:g}=await loaded();assert.equal(g.renderer.buttons.filter(b=>b.id.startsWith('module:')).length,0);click(g,'workshop');assert.equal(g.screen,'workshop');click(g,'gear-next');assert.equal(g.renderer.buttons.filter(b=>b.id.startsWith('module:')).length,6);assert.ok(g.renderer.buttons.some(b=>b.id==='module:rocket'));for(const size of [{width:320,height:480},{width:430,height:932}]){g.resize(size);for(const screen of ['garage','workshop','module']){g.screen=screen;g.selected='cargo';g.draw();assert.ok(g.renderer.buttons.every(b=>b.x>=0&&b.x+b.w<=390&&b.y>=0&&b.y+b.h<=g.renderer.layout.h),screen);}g.start();g.run.rogue.offer=['rocket','laser','mine'];g.screen='upgrade';g.draw();assert.ok(g.renderer.buttons.every(b=>b.x>=0&&b.x+b.w<=390&&b.y>=0&&b.y+b.h<=g.renderer.layout.h));}});
test('game loads production artwork; missing image is reported and never silently replaced',async()=>{const h=await loaded();assert.equal(h.game.loaded,true);assert.equal(h.game.progress,1);assert.deepEqual(h.paths.sort(),Object.values(IMAGES).sort());assert.ok(h.game.renderer.buttons.some(b=>b.id==='start'));const broken=harness({},IMAGES.atlas);await assert.rejects(broken.game.load(),/atlas-v1/);assert.equal(broken.game.loaded,false);});
test('touch cancellation and major resize release steering; pause overlay cannot click hidden actions',async()=>{const {game:g}=await loaded();click(g,'start');g.pointerDown(80,710,1);g.pointerMove(130,710,1);assert.equal(g.input.x,1);g.pointerCancel(2);assert.equal(g.input.x,1);g.pointerCancel(1);assert.equal(g.input.x,0);g.pointerDown(80,710,1);g.pointerMove(130,710,1);g.resize({width:320,height:568});assert.deepEqual(g.input,{x:0,y:0});g.action('pause');const t=g.run.time;g.action('action');g.action('boost');frames(g,3);assert.equal(g.run.time,t);assert.equal(g.run.interacting,false);assert.equal(g.run.player.boostCooldown,0);});
test('background freezes combat, reload retains run and installed modules, no offline catch-up',async()=>{const p={...newProfile(),bank:100,owned:['side'],equipped:['side']},h=await loaded({[SAVE_KEY]:p,'other-game':{value:'keep'}}),g=h.game;g.start();g.keyboard('w',true);frames(g,3);g.setVisible(false);const before=g.run.snapshot();frames(g,100,3000);assert.deepEqual(g.run.snapshot(),before);g.setVisible(true);assert.equal(g.screen,'pause');const restored=await loaded(Object.fromEntries(h.data));assert.equal(restored.game.run.time,before.time);assert.deepEqual(restored.game.run.modules,['side']);restored.game.start();frames(restored.game,.1,1e9);assert.ok(restored.game.run.time-before.time<.11);assert.deepEqual(restored.data.get('other-game'),{value:'keep'});});
test('results credit once in one save, reload never replays rewards, upgrades survive and remain locked during a run',async()=>{const h=await loaded(),g=h.game;g.start();g.run.player.cargo=MODULE_BY_ID.cargo.cost+20;g.run.finish(true);frames(g,.1);assert.equal(g.profile.bank,MODULE_BY_ID.cargo.cost+20);assert.equal(g.profile.runs,1);frames(g,3,100);assert.equal(g.profile.bank,MODULE_BY_ID.cargo.cost+20);assert.equal(h.data.get(SAVE_KEY).run,null);const r=await loaded(Object.fromEntries(h.data));assert.equal(r.game.profile.bank,MODULE_BY_ID.cargo.cost+20);assert.equal(r.game.run,null);click(r.game,'workshop');click(r.game,'module:cargo');click(r.game,'equip');assert.equal(r.game.profile.bank,20);assert.deepEqual(r.game.profile.equipped,['cargo']);r.game.start();r.game.action('pause');r.game.action('save-home');r.game.action('workshop');r.game.action('module:cargo');r.game.action('equip');assert.deepEqual(r.game.profile.equipped,['cargo']);assert.equal(r.game.profile.bank,20);});
test('storage writes are bounded, and completed renders reuse the same cached sprites',async()=>{const {game:g,writes}=await loaded();g.start();const before=writes.length;frames(g,9);assert.ok(writes.length-before<=2);const caches=g.renderer.sprites.size;for(let i=0;i<300;i++)g.draw();assert.equal(g.renderer.sprites.size,caches);});
test('edge touch starts at rest; visual stick clamping never offsets the steering origin',async()=>{const {game:g}=await loaded();g.start();g.pointerDown(8,822,1);assert.deepEqual(g.joy.origin,{x:8,y:822});assert.deepEqual(g.input,{x:0,y:0});g.pointerMove(8,822,1);assert.deepEqual(g.input,{x:0,y:0});assert.equal(g.joy.base.x,44);assert.equal(g.joy.base.y,796);g.pointerMove(25,822,1);assert.ok(g.input.x>.48&&g.input.x<.49);assert.equal(g.input.y,0);g.pointerUp(25,822,1);assert.deepEqual(g.input,{x:0,y:0});});
test('kill and ram feedback never freeze driving or steal simulation time',async()=>{
  const games=[(await loaded()).game,(await loaded()).game];
  for(const g of games){g.start();g.run.enemies=[];g.run.spawnClock=999;g.run.caches.forEach(c=>c.open=true);g.run.convoy.freight.forEach(f=>f.grace=999);g.keyboard('d',true);g.frame(0);}
  for(let i=1;i<=180;i++){if(i%12===0)games[1].run.emit(i%24===0?'ram':'kill');for(const g of games)g.frame(i*1000/60);}
  assert.equal(games[0].run.time,games[1].run.time);assert.deepEqual(games[0].run.player,games[1].run.player);assert.ok(Math.abs(games[0].run.time-3)<1e-8);
});
test('utility keys do not cancel touch steering, and releasing touch does not cancel held keyboard input',async()=>{
  const {game:g}=await loaded();g.start();g.pointerDown(80,710,1);g.pointerMove(130,710,1);assert.equal(g.input.x,1);
  g.keyboard('shift',true);assert.equal(g.input.x,1);g.keyboard('shift',false);assert.equal(g.input.x,1);
  g.keyboard('w',true);assert.deepEqual(g.input,{x:0,y:-1});g.pointerUp(130,710,1);assert.deepEqual(g.input,{x:0,y:-1});g.keyboard('w',false);assert.deepEqual(g.input,{x:0,y:0});
});
test('holding Shift cannot auto-trigger another boost after its cooldown',async()=>{
  const {game:g}=await loaded();g.start();g.keyboard('shift',true);g.run.player.boostCooldown=0;g.run.player.boostTime=0;g.keyboard('shift',true);assert.equal(g.run.player.boostTime,0);g.keyboard('shift',false);g.keyboard('shift',true);assert.equal(g.run.player.boostTime,DRIVE.boostTime);
});
test('second finger boosts on press without releasing steering; a cooling button cannot become a joystick',async()=>{const {game:g}=await loaded();g.start();g.pointerDown(80,740,1);g.pointerMove(125,740,1);const steering={...g.input},b=g.renderer.buttons.find(b=>b.id==='boost');g.pointerDown(b.x+b.w/2,b.y+b.h/2,2);assert.equal(g.run.player.boostTime,DRIVE.boostTime);assert.deepEqual(g.input,steering);assert.equal(g.joy.id,1);g.pointerUp(b.x+b.w/2,b.y+b.h/2,2);assert.deepEqual(g.input,steering);assert.equal(g.run.player.boostCooldown,DRIVE.boostCooldown);g.pointerCancel(1);g.draw();const disabled=g.renderer.buttons.find(b=>b.id==='boost');assert.ok(disabled);g.pointerDown(disabled.x+31,disabled.y+31,3);assert.equal(g.joy,null);assert.deepEqual(g.input,{x:0,y:0});g.pointerUp(disabled.x+31,disabled.y+31,3);assert.equal(g.run.player.boostCooldown,DRIVE.boostCooldown);});
test('nearby cache collects automatically without a parking task or duplicate reward',async()=>{const {game:g}=await loaded();g.start();g.run.enemies=[];g.run.spawnClock=999;const cache=g.run.caches[0];g.run.player.x=cache.x;g.run.player.y=cache.y;frames(g,.2);assert.equal(cache.open,true);assert.equal(g.run.player.cargo,12);assert.equal(g.run.rogue.xp,6);assert.ok(!g.renderer.buttons.some(b=>b.id==='loot:0'));frames(g,1,210);assert.equal(g.run.player.cargo,12);});
test('route chart pauses combat and roof taps mark the nearest safe road, not an unreachable building',async()=>{
  const {game:g}=await loaded();g.start();g.action('map');const time=g.run.time;frames(g,20);assert.equal(g.run.time,time);assert.ok(g.renderer.buttons.every(b=>['close-map','chart','return-guide'].includes(b.id)));
  const r=g.renderer.chartRect,p={x:r.x+670/WORLD.w*r.w,y:r.y+1700/WORLD.h*r.h};g.pointerDown(p.x,p.y,1);g.pointerUp(p.x,p.y,1);assert.equal(g.screen,'play');assert.ok(g.waypoint);assert.equal(g.run.blocked(g.waypoint.x,g.waypoint.y,29),false);assert.deepEqual(g.input,{x:0,y:0});assert.equal(g.lastTime,null);
});
